// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://jjmurmqpkopjmzzbzunr.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqbXVybXFwa29wam16emJ6dW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNTE2MTUsImV4cCI6MjA4NDgyNzYxNX0.G_0MYSZPanAnbYOAMzrswUOls-5PQKz10LA4ZyH0hDE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});